defaults:
  - override hydra/launcher: joblib

hydra:
  launcher:
    n_jobs: 20

seed: 789243
dir: '/home/declan/current/canvi/canvi/arch'

data:
  n_pts: 1000
  T: 100

training:
  device: 'cuda:6'
  epochs: 25000
  lr: 1e-4
  grad_clip: 1
  mb_size: 1
  loss: 'elbo'

encoder:
  type: 'flow'
  run: true

smc:
  K: 1000
  skip: false
  only: false
  index: 0

plots:
  index: 0
  losses: ['elbo', 'iwbo', 'favi']
  alphas: [.5, .25, .1, .05]
  lr: 1e-4
  n_test_points: 1000